#ifndef _ADSL_TAGS_H_
#define _ADSL_TAGS_H_

#define ADSLTAG_MIGRATION_CORRE_REQUEST "MIGRATION_CORRE_REQUEST"
//#define ADSLTAG_REQUEST_MANUALCNT

#define ADSLTAG_BREAKDOWN_MIGRATION "MIGRATION_BREAKDOWN"

#endif /* adsl/tags.h */
